### ISSUE TITLE
fun search is missing 

### ISSUE THREAD

**Issue by psikosen** [google-deepmind/funsearch#4]
Is the requirements file missing I keep getting `implementation.funsearch` is missing

`Traceback (most recent call last):
File
/Users/raymond.gonzalez/Documents/fun/funsearch/implementation/funsearch-py", line 20,
in < module>
from funsearch. implementation import code manipulation
File "/Users/raymond.gonzalez/Documents/fun/funsearch/implementation/funsearch.py", line 20, in ‹module> from funsearch. implementation import code_manipulation
ModuleNotFoundError: No module named
'funsearch implementation'; 'funsearch' is not a package`

**Comment by Rubiel1** [comment]
Hi,

Take a look at this two links [adding a init file](https://stackoverflow.com/questions/54333865/python-no-module-named-error-package-is-not-a-package) and [what to put on the init file](https://stackoverflow.com/questions/67100775/how-to-write-python-init-py-file-for-module)

I added $__init__.py$ files to their folders, and to use the dot notation I wrote
```from .implementation import * on the init file of the folder funsearch.```

From outside of the folder funsearch I can do:

```from funsearch.implementation import programs_database_test as test``` and it gives me no problem.

Also, I renamed the funsearch.py file to fun_search.py (but this may not be necessary).

I originally solved it here [in this post](https://stackoverflow.com/questions/77737111/errors-while-running-deepminds-publicly-available-code-regarding-their-recent-m/77797993?noredirect=1#comment137166109_77797993)

**Comment by psikosen** [comment]
@Rubiel1  I really appreciate your help. I tried this and I am still running into the same issues :'(. Could you possibly send me or upload the repo with your changes if possible ?

**Comment by Rubiel1** [comment]
Just to confirm:

1.  you added two init files,  one on the implementation folder (and the file was empty), and  
2.  one on the funsearch folder (and the file contains the line ```from .implementation import *```).
3.  And you modified the name of the file funsearch.py to fun_search.py

And you still got the exactly same error

**Comment by pwnedzen** [comment]
> Just to confirm:
> 
> 1. you added two init files,  one on the implementation folder (and the file was empty), and
> 2. one on the funsearch folder (and the file contains the line `from .implementation import *`).
> 3. And you modified the name of the file funsearch.py to fun_search.py
> 
> And you still got the exactly same error

I can confirm, I the exact same error 

```File "/home/cake/fu/funsearch/implementation/fun_search.py", line 22, in <module>
    from funsearch.implementation import code_manipulation
ModuleNotFoundError: No module named 'funsearch'```

**Comment by HJ9412** [comment]
Move your funsearch folder to the implementation folder.
Or you may copy everything in the implementation folder to one step up.

**Comment by psikosen** [comment]
@Rubiel1  Yes, after doing all of that, I still get the same error.

**Comment by Rubiel1** [comment]
@psikosen did you also try what @HJ9412 suggested?

**Comment by psikosen** [comment]
@Rubiel1  Thanks I got it !

**Comment by pwnedzen** [comment]
> @psikosen did you also try what @HJ9412 suggested?
> 
> @pwnedzen this is a slightly different error message. Can you try what @HJ9412 suggested?

I just tried what @HJ9412 suggested, and it is now working. Thanks @Rubiel1 and @HJ9412!

**Comment by HAFDIAHMED** [comment]
hello @psikosen  and @Rubiel1 please guys i got the same issue also i followed all the steps from @Rubiel1  but still the same issue would any please write his own code worked ?

**Comment by Visheeeee** [comment]
Hello, I have been trying to setup funsearch on my local as well but have been facing the same issue. Could you please assist me with the same? I have tried placing two init files as suggested earlier and even tried eliminating the implementation folder altogether, just keeping all the code under the funsearch folder but still face the same issue.
